repos:
-   repo: git@github.com:pre-commit/pre-commit-hooks
    rev: 4078cbedf0360dce2b7cd02cb2812fc50b76b98d
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://github.com/pre-commit/mirrors-jshint
    rev: v2.13.6
    hooks:
    -   id: jshint
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.60.0
    hooks:
    -   id: scss-lint
